In [1]:
import pandas as pd

C:\Users\jyosn\AppData\Local\Temp\ipykernel_16380\4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [3]:
df_train=pd.read_csv("C:\\Users\\jyosn\\Documents\\GitHub\\Predictive-Maintenance\\Datasets\\train_FD001.csv")
df_train.drop(columns=['Sensor3','Sensor4','Sensor8','Sensor13','Sensor19','Sensor21','Sensor22'],inplace=True)

In [4]:
df_train.head()

,Engine,Cycles,Sensor1,Sensor2,Sensor5,Sensor6,Sensor7,Sensor9,Sensor10,Sensor11,Sensor12,Sensor14,Sensor15,Sensor16,Sensor17,Sensor18,Sensor20,Sensor23,Sensor24,Remaining Cycles
0,1,1,-0.0007,-0.0004,641.82,1589.70,1400.60,21.61,554.36,2388.06,9046.19,47.47,521.66,2388.02,8138.62,8.4195,392,39.06,23.4190,191
1,1,2,0.0019,-0.0003,642.15,1591.82,1403.14,21.61,553.75,2388.04,9044.07,47.49,522.28,2388.07,8131.49,8.4318,392,39.00,23.4236,190
2,1,3,-0.0043,0.0003,642.35,1587.99,1404.20,21.61,554.26,2388.08,9052.94,47.27,522.42,2388.03,8133.23,8.4178,390,38.95,23.3442,189
3,1,4,0.0007,0.0000,642.35,1582.79,1401.87,21.61,554.45,2388.11,9049.48,47.13,522.86,2388.08,8133.83,8.3682,392,38.88,23.3739,188
4,1,5,-0.0019,-0.0002,642.37,1582.85,1406.22,21.61,554.00,2388.06,9055.15,47.28,522.19,2388.04,8133.80,8.4294,393,38.90,23.4044,187

In [8]:
##lagging

df_train["lag1"]=df_train['Remaining Cycles'].shift(10)
df_train.head()
df_train["lag2"]=df_train['Remaining Cycles'].shift(20)
df_train["lag3"]=df_train['Remaining Cycles'].shift(30)
df_train["lag4"]=df_train['Remaining Cycles'].shift(40)
df_train["lag5"]=df_train['Remaining Cycles'].shift(50)
df_train.head(20)

,Engine,Cycles,Sensor1,Sensor2,Sensor5,Sensor6,Sensor7,Sensor9,Sensor10,Sensor11,...,Sensor18,Sensor20,Sensor23,Sensor24,Remaining Cycles,lag1,lag2,lag3,lag4,lag5
0,1,1,-0.0007,-0.0004,641.82,1589.70,1400.60,21.61,554.36,2388.06,...,8.4195,392,39.06,23.4190,191,NaN,NaN,NaN,NaN,NaN
1,1,2,0.0019,-0.0003,642.15,1591.82,1403.14,21.61,553.75,2388.04,...,8.4318,392,39.00,23.4236,190,NaN,NaN,NaN,NaN,NaN
2,1,3,-0.0043,0.0003,642.35,1587.99,1404.20,21.61,554.26,2388.08,...,8.4178,390,38.95,23.3442,189,NaN,NaN,NaN,NaN,NaN
3,1,4,0.0007,0.0000,642.35,1582.79,1401.87,21.61,554.45,2388.11,...,8.3682,392,38.88,23.3739,188,NaN,NaN,NaN,NaN,NaN
4,1,5,-0.0019,-0.0002,642.37,1582.85,1406.22,21.61,554.00,2388.06,...,8.4294,393,38.90,23.4044,187,NaN,NaN,NaN,NaN,NaN
5,1,6,-0.0043,-0.0001,642.10,1584.47,1398.37,21.61,554.67,2388.02,...,8.4108,391,38.98,23.3669,186,NaN,NaN,NaN,NaN,NaN
6,1,7,0.0010,0.0001,642.48,1592.32,1397.77,21.61,554.34,2388.02,...,8.3974,392,39.10,23.3774,185,NaN,NaN,NaN,NaN,NaN
7,1,8,-0.0034,0.0003,642.56,1582.96,1400.97,21.61,553.85,2388.00,...,8.4076,391,38.97,23.3106,184,NaN,NaN,NaN,NaN,NaN
8,1,9,0.0008,0.0001,642.12,1590.98,1394.80,21.61,553.69,2388.05,...,8.3728,392,39.05,23.4066,183,NaN,NaN,NaN,NaN,NaN
9,1,10,-0.0033,0.0001,641.71,1591.24,1400.46,21.61,553.59,2388.05,...,8.4286,393,38.95,23.4694,182,NaN,NaN,NaN,NaN,NaN
10,1,11,0.0018,-0.0003,642.28,1581.75,1400.64,21.61,554.54,2388.05,...,8.4340,392,38.94,23.4787,181,191.0,NaN,NaN,NaN,NaN
11,1,12,0.0016,0.0002,642.06,1583.41,1400.15,21.61,554.52,2388.09,...,8.3938,391,39.06,23.3660,180,190.0,NaN,NaN,NaN,NaN
12,1,13,-0.0019,0.0004,643.07,1582.19,1400.83,21.61,553.44,2388.12,...,8.4152,393,38.93,23.2757,179,189.0,NaN,NaN,NaN,NaN
13,1,14,0.0009,-0.0000,642.35,1592.95,1399.16,21.61,554.48,2388.09,...,8.3964,393,39.18,23.3826,178,188.0,NaN,NaN,NaN,NaN
14,1,15,-0.0018,-0.0003,642.43,1583.82,1402.13,21.61,553.64,2388.11,...,8.4199,391,38.99,23.3500,177,187.0,NaN,NaN,NaN,NaN
15,1,16,0.0006,0.0005,642.13,1587.98,1404.50,21.61,553.94,2388.05,...,8.3936,392,38.97,23.4550,176,186.0,NaN,NaN,NaN,NaN
16,1,17,0.0002,0.0002,642.58,1584.96,1399.95,21.61,553.80,2388.06,...,8.4542,392,38.81,23.3319,175,185.0,NaN,NaN,NaN,NaN
17,1,18,-0.0031,-0.0001,642.62,1591.04,1396.12,21.61,554.20,2388.05,...,8.4028,392,38.89,23.3987,174,184.0,NaN,NaN,NaN,NaN
18,1,19,0.0032,-0.0003,641.79,1587.56,1400.35,21.61,554.18,2388.04,...,8.4321,391,38.80,23.3464,173,183.0,NaN,NaN,NaN,NaN
19,1,20,-0.0037,0.0001,643.04,1581.11,1405.23,21.61,554.81,2388.05,...,8.4210,392,39.03,23.4220,172,182.0,NaN,NaN,NaN,NaN